version: '3.2'

services:
  redis:
    build: ./.docker/redis
    image: orders-api-redis
    container_name: orders-api-redis
    restart: always
    ports:
      - "16379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 5

